### ISSUE TITLE
setContents line 62 of BaseLootTableProvider is invalid

### ISSUE THREAD

**Issue by Kairi-lol** [McJty/TutorialV3#1]
when trying to follow along I am unable to setContents(type) line 62 of BaseLootTableProvider it shows as red and invalid.
![image](https://user-images.githubusercontent.com/23045776/147548197-f71d0f09-ded5-45e7-86d5-c1238e9f7944.png)

I am using parchment mappings but I have changed back to default and the issue persists.

**Comment by McJty** [comment]
Can you show me your build.gradle? For me this is definitely working. Also did you refresh gradle after changing mappings?

**Comment by Kairi-lol** [comment]
I have refreshed it after changing mappings, still learning so I'm sure I messed up somewhere simple. build.gradle is with the rest of my mod here https://github.com/Mylezz/warped-abyss 

thanks for looking

**Comment by McJty** [comment]
You are using parchment mappings for 1.17:

    mappings channel: 'parchment', version: '2021.08.15-1.17.1'

Switch to the 1.18 parchment mappings

**Comment by Kairi-lol** [comment]
Durr!! Thank you so much!
